all:
	openscad -o stl/64x32\ -\ 4mm\ pitch.stl 64x32\ -\ 4mm\ pitch.scad
	openscad -o stl/64x32\ -\ 4mm\ pitch\ -\ Part\ 1.stl 64x32\ -\ 4mm\ pitch\ -\ Part\ 1.scad
	openscad -o stl/64x32\ -\ 4mm\ pitch\ -\ Part\ 2.stl 64x32\ -\ 4mm\ pitch\ -\ Part\ 2.scad
