# Generated by Django 3.2.8 on 2022-08-25 18:25

from django.db import migrations, models
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('script', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('ca', 'Catalan'), ('cn', 'Chinese'), ('cs', 'Czech'), ('nl', 'Dutch'), ('en-us', 'English (US)'), ('en-gb', 'English (British)'), ('en-in', 'English (Indian)'), ('es', 'Esperanto'), ('fa', 'Farsi'), ('fr', 'French'), ('de', 'German'), ('hi', 'Hindi'), ('it', 'Italian'), ('ja', 'Japanese'), ('kz', 'Kazakh'), ('pl', 'Polish'), ('ru', 'Russian'), ('es', 'Spanish'), ('tr', 'Turkish'), ('vn', 'Vietnamese'), ('uk', 'Ukranian')], default='en-us', max_length=32)),
                ('prioritise_accuracy', models.BooleanField(default=False)),
                ('image', smartfields.fields.ImageField(blank=True, null=True, upload_to='')),
            ],
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
    ]
