# Generated by Django 3.2.16 on 2023-01-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
